export { default as DiceBase } from "./DiceBase";
export { default as D3 } from "./D3";
export { default as D4 } from "./D4";
export { default as D6 } from "./D6";
export { default as D8 } from "./D8";
export { default as D10 } from "./D10";
export { default as D12 } from "./D12";
export { default as D20 } from "./D20";
export { default as Coin } from "./Coin";
export { default as Thumbtack } from "./Thumbtack";
export * from "./Dice.types";
